language: java
jdk:
  - oraclejdk8
app: work-continuous
script:
- mvn test
notifications:
  email:
    recipients:
      - leonardo.rsil@gmail.com    
    on_success: always # default: change
    on_failure: always # default: always