language: java
jdk:
  - oraclejdk8
app: work-continuous
script:
- mvn test
- "mvn cobertura:cobertura"

after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    recipients:
      - leonardo.rsil@gmail.com    
    on_success: always # default: change
    on_failure: always # default: always
