# LOGGING
logging:
  file: build/work-continuous.log
  level:
    org.una.work: INFO
    org.springframework: WARN
    org.hibernate: WARN

# DATABASE
spring:
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create



# LIQUIBASE
liquibase:
  enabled: false
  change-log: classpath:data/config/master.xml
  url: ${JDBC_DATABASE_URL}

